Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(multiplexing_VH_decoder.py:558142): Gdk-CRITICAL **: 17:05:17.586: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(multiplexing_VH_decoder.py:558142): Gdk-CRITICAL **: 17:05:17.589: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
inputs:
['../multiplexing_VH_decoder.py', '2', '100000', '1', '0', '101', '2', '../input_matrices/N8_K2_symmetric']
start simulation
2024-04-23 17:05:17.733197
simulation finished
2024-04-23 18:29:48.615487
saved the results to ../results/results_HGP_n=8_m=2_r=0.0-1.0_as=2.json
